### ISSUE TITLE
update to node-sass: 4.11.0

### ISSUE THREAD

**Issue by thiagorova** [Bradshaw/electron-middle-sass#1]
Hi! first of all, thanks for this cool package (and the whole middleware idea, its pretty great)

so... as far as my understanding goes, node-sass 4.8.3 only supports all the way to node 8. Do you think it'll be possible to update node-sass anytime soon so it can support node 10 (plus some extra sass features)?

thanks again!

**Comment by tecc** [comment]
node-sass was updated, see #2.

**Comment by Bradshaw** [comment]
Closed thanks to @tecc's work on #2
